language: node_js
before_script:
  - yarn boot
branches:
  only:
    - master
dist: precise
addons:
  firefox: 50.0
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
  directories:
    - node_modules
    - packages/react-instantsearch/node_modules
    - packages/react-instantsearch-theme-algolia/node_modules
env:
  global:
  - ARGOS_TOKEN=da82cbbe3add183c6adb18f5c61da515d9bf99dd
