language: node_js
before_script:
  - yarn boot
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
    - packages/react-instantsearch/node_modules
    - packages/react-instantsearch-theme-algolia/node_modules
