blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/algolia/react-instantsearch/discussions/new
    about: Request a feature to add to React InstantSearch.
  - name: Ask a Question
    url: https://github.com/algolia/react-instantsearch/discussions/new
    about: Ask questions and discuss with other community members.
